Таблица с удаляемыми строками
js-tasks-ru/jsbasic-20220211_ea-husainova pull request #11
Opened 2022-03-16 14:47 UTC by Elya-Husainova

2022-03-16 15:10 UTC, jsru commented
Добавляю преподавателя (@SinimaWath) для код-ревью.

2022-03-17 13:16 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @SinimaWath

2022-03-18 13:02 UTC, jsru commented
Проверьте, пожалуйста, ваше решение, не все тесты прошли (PR не будет принят до тех пор, пока **все** добавленные задачи не будут решены).

2022-03-18 13:09 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @SinimaWath

2022-03-18 13:25 UTC, SinimaWath requested changes

2022-03-18 13:25 UTC, SinimaWath commented on 6-module/3-task/index.js
> +      let slide = slides[self.slideNumber];
вместо того, чтобы использовать self, перепиши функцию на стрелочную.

У которой в замыкании сохранен this

2022-03-18 14:09 UTC, Elya-Husainova commented on 6-module/3-task/index.js
> +      let slide = slides[self.slideNumber];
✓ Переписала на стрелочные функции

2022-03-18 14:10 UTC, jsru commented
Добавляю преподавателя (@SinimaWath) для код-ревью.

2022-03-21 05:50 UTC, SinimaWath approved these changes
все круто!

2022-03-21 05:51 UTC, merged